language: node_js
node_js:
    - "0.10"
notifications:
    email:
        - me@oyvindrobertsen.com
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y texlive
    - sudo apt-get install -y rubber
